---
title: "LISTA 8"
subtitle: "ANÁLISE MULTIVARIADA 1"
author: "Tailine J. S. Nonato"
date: "12/14/2023"
format: pdf
---

```{r}
#| message: false
#| warning: false
#| echo: false
pacman::p_load(tidyverse,knitr)
```

# 11.1
```{r}
#| message: false
#| warning: false
#| echo: false
x1<- matrix(c(3,2,4,7,4,7),3,2)
x2<-matrix(c(6,5,4,9,7,8),3,2)
meanx1<- matrix(c(3,6),2,1)
meanx2<- matrix(c(5,8),2,1)
s<-matrix(c(1,1,1,2),2,2)
```

## Item A

$$ \tilde{y} = (\bar{x}_{1} - \bar{x}_{2})' \hspace{1pt} S_{\text{pooled}}^{-1} \hspace{1pt} x = \tilde{\alpha}' \hspace{1pt} x $$

```{r}
#| message: false
#| warning: false
#| echo: false
sinv<- solve(s)
sinv
```

Assim, 
$$\tilde{y} = \left(\begin{bmatrix}
3 \\
6 
\end{bmatrix} - \begin{bmatrix}
5 \\
8 
\end{bmatrix}\right)' \begin{bmatrix}
2 & -1\\
-1 & 1
\end{bmatrix} \hspace{1pt} x 
$$


$$\tilde{y} = \tilde{\alpha}' \hspace{1pt} x 
$$

$$\tilde{y} = \begin{bmatrix}
-2 & 0
\end{bmatrix} \hspace{1pt} x 
$$

$$\tilde{y} = -2x_{1} 
$$


## Item B 

$$\hat{m}=\frac{1}{2}(\hat{y}_1+\hat{y}_2)=\frac{1}{2}(\mathbf{\hat{a}'\bar{x}_1+\hat{a}'\bar{x}_2})= 8$$

Portanto, devemos colocar $x'_0$ na população $\pi _1$ se $\hat{y}_0=[2 \ \ 7]x_0 \geq \hat{m}=$ 8. Caso contrário, devemos atribuir $x_0$ para a população $\pi_2$.
Neste caso, $x_0$ calculado = -4; portanto, atribuímos este à população $\pi_1$


# 11.2

# 11.4

# 11.7

# 11.8

# 11.10

# 11.11

# 11.12

# 11.13

# 11.16

# 11.23

# 11.32

# Q13
