---
title: "Centro Colaborador de Apoio ao Monitoramento e à Gestão de Programas Educacionais do Centro Oeste"
subtitle: "Monitoramento e Apoio às UEx do PDDE Básico e  PDDE Ações Integradas"
author: "Tailine J. S. Nonato"
format: pdf
---

```{r}
#| echo: false
#| message: false
if (!require(pacman)) install.packages("pacman")
pacman::p_load(tidyverse, knitr, openxlsx)
setwd("C:/Users/User/Documents/GitHub/gradest-1/PDDE/entrega 7")
#setwd("/Users/tailine.nonato/Documents/VSCode/PDDE/entrega 1")
```

# Extração

## Censo Escolar 2023
```{r}	
censo23 <- read.csv("microdados_ed_basica_2023.csv", encoding = "latin1")
kable(head(censo23))
```

## PDDE 2024
Descrição da manipulação:

- Importação dos dados no Consulta Escola

- Conversão de xls para csv utilizando CloudConvert

- Importação dos dados no R

```{r}
pdde24 <- read_csv2("situacao-atendimento-entidade.csv")
```


# Transformação

Censo Escolar 2022 na região Centro-Oeste:
```{r}
#censo22_co <- censo22 %>%
#    filter(NO_REGIAO == "Centro-Oeste")

#write.csv(censo22_co, "dados/censo22_co.csv", row.names = FALSE)
censo22_co <- read.csv("dados/censo22_co.csv")
```

PDDE 2023 com pagos e não-pagos:
```{r}	
pdde_pagos$fonte <- "pdde_pagos"
pdde_naopagos$fonte <- "pdde_naopagos"
pdde <- rbind(pdde_pagos, pdde_naopagos)
```

Cruzamento de informações Censo e PDDE utilizando o código da escola como chave:
```{r}
censo22_co$CO_ENTIDADE <- as.character(censo22_co$CO_ENTIDADE)
pdde$Código.Escola <- as.character(pdde$Código.Escola)

dados <- censo22_co %>% left_join(pdde, by = c("CO_ENTIDADE" = "Código.Escola"))
```

# Loading/Exportação

```{r}
write.csv(dados, "dados/base_completa.csv")
```