---
title: "Centro Colaborador de Apoio ao Monitoramento e à Gestão de Programas Educacionais do Centro Oeste"
subtitle: "Monitoramento e Apoio às UEx do PDDE Básico e  PDDE Ações Integradas"
author: "Tailine J. S. Nonato"
format: pdf

---

# Entrega 4: Análise de Saldos e Repasses

## Repasses do PDDE Básico em 2023
```{r}
#| message: false
#| warning: false
#| echo: false
if (!require(pacman)) install.packages("pacman")
pacman::p_load(tidyverse, knitr, readxl, openxlsx, kableExtra)
#setwd("C:/Users/User/Documents/GitHub/gradest-1/PDDE/entrega 4")
setwd("/Users/tailine.nonato/Documents/gradest/PDDE/entrega 4")
```


```{r}
#| message: false
#| warning: false
#| echo: false


dados <- read_excel("situacao-atendimento-entidade.xlsx")

dados3 <- dados %>%
  group_by(Cod_Escola, Quantidade) %>%
  summarise(ValorTotal = sum(ValorTotal), ValorCusteio = sum(ValorCusteio), ValorCapital = sum(ValorCapital))


kable(format(nrow(dados3), big.mark = "."),, align='l', col.names = "Número de escolas")%>%
  kable_styling(full_width = F, position = "left")%>%
  footnote(general = "Consulta Escola / FNDE",
  general_title = "Fonte:")

```

### Tabela 1: Soma, Média e Desvio Padrão

```{r}
#| message: false
#| warning: false
#| echo: false

# Calculando a soma, média e desvio padrão
soma <- round(sum(dados3$ValorTotal),2)
media <- round(mean(dados3$ValorTotal),2)
desvio <- round(sd(dados3$ValorTotal),2)

soma_custeio <- round(sum(dados3$ValorCusteio),2)
media_custeio <- round(mean(dados3$ValorCusteio),2)
desvio_custeio <- round(sd(dados3$ValorCusteio),2)

soma_capital <- round(sum(dados3$ValorCapital),2)
media_capital <- round(mean(dados3$ValorCapital),2)
desvio_capital <- round(sd(dados3$ValorCapital),2)

soma_custeio_perc <- sum(dados3$ValorCusteio)/sum(dados3$ValorTotal)
soma_capital_perc <- sum(dados3$ValorCapital)/sum(dados3$ValorTotal)
media_custeio_perc <- mean(dados3$ValorCusteio)/mean(dados3$ValorTotal)

media_capital_perc <- mean(dados3$ValorCapital)/mean(dados3$ValorTotal)
desvio_custeio_perc <- sd(dados3$ValorCusteio)/sd(dados3$ValorTotal)
desvio_capital_perc <- sd(dados3$ValorCapital)/sd(dados3$ValorTotal)

estatisticas1 <- data.frame("Soma" = c(soma, soma_custeio, soma_custeio_perc, soma_capital, soma_capital_perc),
                           "Média" = c(media, media_custeio, media_custeio_perc, media_capital, media_capital_perc),
                           "Desvio Padrão" = c(desvio, desvio_custeio, desvio_custeio_perc, desvio_capital, desvio_capital_perc))

rownames(estatisticas1) <- c("Valor Total", "Valor Custeio", "Valor Custeio (%)", "Valor Capital", "Valor Capital (%)")

# -------------------------------------------

# Custeio percentual to %, decimal mark to comma
soma_custeio_perc <- paste0(round(soma_custeio_perc*100, 2), "%")
media_custeio_perc <- paste0(round(media_custeio_perc*100, 2), "%")
desvio_custeio_perc <- paste0(round(desvio_custeio_perc*100, 2), "%")

# Capital percentual to %
soma_capital_perc <- paste0(round(soma_capital_perc*100, 2), "%")
media_capital_perc <- paste0(round(media_capital_perc*100, 2), "%")
desvio_capital_perc <- paste0(round(desvio_capital_perc*100, 2), "%")

# Valor Total to R$
soma <- paste0("R$", format(soma, big.mark = ".", decimal.mark = ","))
media <- paste0("R$", format(media, big.mark = ".", decimal.mark = ","))
desvio <- paste0("R$", format(desvio, big.mark = ".", decimal.mark = ","))

# Valor Custeio to R$
soma_custeio <- paste0("R$", format(soma_custeio, big.mark = ".", decimal.mark = ","))
media_custeio <- paste0("R$", format(media_custeio, big.mark = ".", decimal.mark = ","))
desvio_custeio <- paste0("R$", format(desvio_custeio, big.mark = ".", decimal.mark = ","))

# Valor Capital to R$
soma_capital <- paste0("R$", format(soma_capital, big.mark = ".", decimal.mark = ","))
media_capital <- paste0("R$", format(media_capital, big.mark = ".", decimal.mark = ","))
desvio_capital <- paste0("R$", format(desvio_capital, big.mark = ".", decimal.mark = ","))

estatisticas <- data.frame("Soma" = c(soma, soma_custeio, soma_capital),
                           "Média" = c(media, media_custeio, media_capital),
                           "Desvio Padrão" = c(desvio, desvio_custeio,desvio_capital))

rownames(estatisticas) <- c("Valor Total", "Valor Custeio", "Valor Capital")
colnames(estatisticas) <- c("Soma", "Média", "Desvio Padrão")

kable(t(estatisticas), align = "l")%>%
  kable_styling(full_width = F, position = "left")%>%
  footnote(general = "Consulta Escola / FNDE",
  general_title = "Fonte:")

```

### Tabela 2: Alocação de Recursos em Custeio e Capital

```{r}
#| message: false
#| warning: false
#| echo: false


percentagem <- data.frame("Alocação" = c(soma_custeio_perc, soma_capital_perc))

rownames(percentagem) <- c("Valor Custeio (%)", "Valor Capital (%)")
colnames(percentagem) <- c("Alocação")

kable(t(percentagem), align = "l")%>%
  kable_styling(full_width = F, position = "left")%>%
  footnote(general = "Consulta Escola / FNDE",
  general_title = "Fonte:")

```	

\vspace{2em}

### Tabela 3: Percentis, Mínimo e Máximo

```{r}
#| message: false
#| warning: false
#| echo: false

# Calculando o mínimo
minimo_total <- min(dados3$ValorTotal)
minimo_custeio <- min(dados3$ValorCusteio)
minimo_capital <- min(dados3$ValorCapital)

# Calculando os percentis
percentis_total <- quantile(dados3$ValorTotal, c(0.1, 0.25, 0.5, 0.75, 0.9))
percentis_custeio <- quantile(dados3$ValorCusteio, c(0.1, 0.25, 0.5, 0.75, 0.9))
percentis_capital <- quantile(dados3$ValorCapital, c(0.1, 0.25, 0.5, 0.75, 0.9))

# Calculando o máximo
maximo_total <- max(dados3$ValorTotal)
maximo_custeio <- max(dados3$ValorCusteio)
maximo_capital <- max(dados3$ValorCapital)

# Criando a tabela para excel
percentis1 <- data.frame("min" = c(minimo_total, minimo_custeio, minimo_capital),
                        "p10" = c(percentis_total[1], percentis_custeio[1], percentis_capital[1]),
                        "p25" = c(percentis_total[2], percentis_custeio[2], percentis_capital[2]),
                        "p50" = c(percentis_total[3], percentis_custeio[3], percentis_capital[3]),
                        "p75" = c(percentis_total[4], percentis_custeio[4], percentis_capital[4]),
                        "p90" = c(percentis_total[5], percentis_custeio[5], percentis_capital[5]),
                        "max" = c(maximo_total, maximo_custeio, maximo_capital))

rownames(percentis1) <- c("Valor Total", "Valor Custeio", "Valor Capital")
colnames(percentis1) <- c("Mínimo", "Percentil 10", "1º Quartil", "Mediana", "3º Quartil", "Percentil 90", "Máximo")


# ------------------------------------

# Formatando para R$
percentis_total <- paste0("R$", format(percentis_total, big.mark = ".", decimal.mark = ","))
percentis_custeio <- paste0("R$", format(percentis_custeio, big.mark = ".", decimal.mark = ","))
percentis_capital <- paste0("R$", format(percentis_capital, big.mark = ".", decimal.mark = ","))

# Formatando para R$
minimo_total <- paste0("R$", format(minimo_total, big.mark = ".", decimal.mark = ","))
minimo_custeio <- paste0("R$", format(minimo_custeio, big.mark = ".", decimal.mark = ","))
minimo_capital <- paste0("R$", format(minimo_capital, big.mark = ".", decimal.mark = ","))

# Formatando para R$
maximo_total <- paste0("R$", format(maximo_total, big.mark = ".", decimal.mark = ","))
maximo_custeio <- paste0("R$", format(maximo_custeio, big.mark = ".", decimal.mark = ","))
maximo_capital <- paste0("R$", format(maximo_capital, big.mark = ".", decimal.mark = ","))

# Criando a tabela
percentis <- data.frame("min" = c(minimo_total, minimo_custeio, minimo_capital),
                        "p10" = c(percentis_total[1], percentis_custeio[1], percentis_capital[1]),
                        "p25" = c(percentis_total[2], percentis_custeio[2], percentis_capital[2]),
                        "p50" = c(percentis_total[3], percentis_custeio[3], percentis_capital[3]),
                        "p75" = c(percentis_total[4], percentis_custeio[4], percentis_capital[4]),
                        "p90" = c(percentis_total[5], percentis_custeio[5], percentis_capital[5]),
                        "max" = c(maximo_total, maximo_custeio, maximo_capital))

rownames(percentis) <- c("Valor Total", "Valor Custeio", "Valor Capital")
colnames(percentis) <- c("Mínimo", "Percentil 10", "1º Quartil", "Mediana", "3º Quartil", "Percentil 90", "Máximo")

percentis <- as.data.frame(t(percentis))
kable(percentis, align='l')%>%
  kable_styling(full_width = F, position = "left")%>%
  footnote(general = "Consulta Escola / FNDE",
  general_title = "Fonte:")

```



### Tabela 4: Frequência de escolas por faixa de valor total recebido

```{r}
#| message: false
#| warning: false
#| echo: false

# Criando a tabela
dados3$faixa <- cut(dados3$ValorTotal, breaks = c(0, 500, 1000, 5000, 10000, 20000, 35000, 50000, 80000, Inf), labels = c("Até R$500", "R$501 a R$1000", "R$1001 a R$5000", "R$5001 a R$10000", "R$10001 a R$20000", "R$20001 a R$35000", "R$35001 a R$50000", "R$50001 a R$80000","Mais de R$80000"))

# Tabela de frequencia
tabela_freq <- table(dados3$faixa)
tabela_freq <- data.frame("Faixa" = names(tabela_freq), "Frequência" = as.numeric(tabela_freq))

# Ordenando a tabela
tabela_freq <- tabela_freq %>%
  mutate(Faixa = factor(Faixa, levels = c("Até R$500", "R$501 a R$1000", "R$1001 a R$5000", "R$5001 a R$10000", "R$10001 a R$20000", "R$20001 a R$35000", "R$35001 a R$50000", "R$50001 a R$80000","Mais de R$80000")))

# Adicionando a coluna de percentual
tabela_freq <- tabela_freq %>%
  mutate(Percentual = paste0(round(Frequência/sum(Frequência)*100, 2),"%"))

# Convert Faixa back to character
tabela_freq$Faixa <- as.character(tabela_freq$Faixa)

# Add the "Total" row
tabela_freq <- rbind(tabela_freq, c("Total", sum(tabela_freq$Frequência), "100%"))

# footnote
kable(tabela_freq, align = "l") %>%
  kable_styling(full_width = F, position = "left")%>%
  footnote(general = "Consulta Escola / FNDE",
  general_title = "Fonte:")

```



```{r}
#| message: false
#| warning: false
#| echo: false

## Verificação de UEx consórcios
# cnpj seduc é diferente de cnpj uex E cnpj uex aparece mais de 2 vezes nos dados
names(dados)

unique(dados$Destinacao)

destinacao <- dados %>%
  filter(Destinacao == "PDDE Basico - 2 Parcela 2022" | Destinacao == "PDDE Basico - 1 Parcela 2022")

cnpjs <- dados %>%
  filter(CNPJ_SEDUC != CNPJ_Ex) %>%
  group_by(CNPJ_Ex) %>%
  summarise(n = n()) 
  
consorcios <- cnpjs %>% filter(n > 2) 

summary(consorcios$n)

# identificar escolas que estão em consórcios
escolas_consorcios <- dados %>%
  filter(CNPJ_Ex %in% consorcios$CNPJ_Ex)

#adicionar numero de vezes que o cnpj aparece
escolas_consorcios <- escolas_consorcios %>%
  left_join(consorcios, by = "CNPJ_Ex")

unique_codes <- unique(escolas_consorcios$CNPJ_Ex)

# Create a vector of new codes
new_codes <- seq_along(unique_codes)

# Create a mapping of old codes to new codes
code_mapping <- setNames(new_codes, unique_codes)

# Replace old codes with new codes in both datasets
escolas_consorcios$cod<- code_mapping[as.character(escolas_consorcios$CNPJ_Ex)]

#tabela de frequencias
kable(t(table(consorcios$n/2)))
```

```{r}	
#| message: false
#| warning: false
#| echo: false


# Exportando todas as tabelas para um arquivo .xlsx

wb <- createWorkbook()
addWorksheet(wb, "Tabela 1")
writeData(wb, "Tabela 1", estatisticas1)
addWorksheet(wb, "Tabela 2")
writeData(wb, "Tabela 2", percentagem)
addWorksheet(wb, "Tabela 3")
writeData(wb, "Tabela 3", percentis1)
addWorksheet(wb, "Tabela 4")
writeData(wb, "Tabela 4", tabela_freq)
addWorksheet(wb, "Escolas Consórcios")
writeData(wb, "Escolas Consórcios", escolas_consorcios)
saveWorkbook(wb, "e4_tabelas_tailine_new.xlsx", overwrite = TRUE)
```