---
title: "Centro Colaborador de Apoio ao Monitoramento e à Gestão de Programas Educacionais do Centro Oeste"
subtitle: "Monitoramento e Apoio às UEx do PDDE Básico e  PDDE Ações Integradas"
author: "Tailine J. S. Nonato"
format: docx
---

# Entrega 3: Análise Crítica

**Objetivo:** avaliar a página do PDDE no site do FNDE de forma a mapear as informações disponíveis e facilitadas aos gestores de escola (Área de Gestores). 

Disponível em: <https://www.gov.br/fnde/pt-br/acesso-a-informacao/acoes-e-programas/programas/pdde>

## ÁREA PARA GESTORES

### 1. Atualização Cadastral

Ao clicar nessa aba, o gestor é direcionado para uma página ainda dentro do site do GOV. São apresentadas informações sobre o momento em que deve ser feita a atualização cadastral e os requisitos para tal.

Ao final da página, encontram-se 2 links: (I) guia de adesão e atualização cadastral e (II) PDDE-WEb. Ambos estão com redirecionamento correto. 

### 2. Cecampes

Ao clicar nessa aba o gestor é direcionado para uma página ainda dentro do site do GOV. A página inicia com uma breve introdução ao que são os Centros Colaboradores de Apoio ao Monitoramento e à Gestão de Programas Educacionais, seguida de:

- Materiais produzidos pelos Cecampes

- Guia do FNDE

- Painel de Informações

- Capacitações

- Cecampe UFG

- Vídeos de Apoio

Todos os links estão em pleno funcionamento. 

Logo depois, é possível encontrar uma explicacação mais detalhada sobre as atribuições dos Cecampes. Por fim, há um espaço com informações de contato de cada Cecampe.

### 3. Comunicados

Ao clicar nessa aba o gestor é direcionado para uma página ainda dentro do site do GOV onde links de notícias/comunicados estão dispostos em ordem cronológica divididos por ano.

O último comunicado foi referente ao aumento dos repasses para escolas indígenas, quilombolas e rurais. 

### 4. Monitore o PDDE

Ao clicar nessa aba o gestor é direcionado para uma página ainda dentro do site do GOV. 

De início são apresentados 3 paineis de monitoramento: (I) Saldos PDDE, (II) IDEGES PDDE e (III) Repasse PDDE.

Há uma breve explicação sobre cada um, no entanto não há link para a visão (I), o link da visão (II) está quebrado e o link da visão (III) está com acesso correto, porém a última atualização dos dados foi em 2022.

É oferecida ao gestor a oportunidade de conhecer a nota da sua entidade e como o IdeGES é calculado através do Painel IdeGEs 2018 a 2021 e das Especificações Técnicas - 2021.

Há também destaque para escolas que receberam alto Ideges em 2021 e 2022. 

Importante ressaltar que no final da página há uma série de redirecionamentos escritos da seguinte forma:

- Para consultar informações sobre a escola, acesse o consulta escola

- Para consultar a situação de adimplência, quanto à prestação de contas de Entidades Executoras (EEx), clique aqui.

- Para consultar a situação de adimplência, quanto à prestação de contas de Unidades Executoras Próprias (UEx), clique aqui.

- Para ter acesso à manuais e orientações sobre o PDDE e Ações Agregadas, clique aqui.

- Para consultar o saldo de ações ativas das escolas, clique aqui. 

- Para consultar o saldo de ações extintas das escolas, clique aqui.


### 5. PDDE Info - Consulta Escola

Ao acessar, o gestor é direcionado para o site do Consulta Escola, o qual a análise já foi realizada na Entrega 2.