---
title: "Lista 2 - Eduardo"
subtitle: "Cálculo de Probabilidade 2"
author: "Tailine J. S. Nonato"
format: pdf
---

# Exercício 1

Seja $X$ uma variável aleatória contínua dada por
$$
f (x) = \begin{cases}
\frac{2}{x^3} & \text{se } x > 1, \\
0 & \text{se } x < 1.
\end{cases}
$$

Considere o evento $B = [X \leq 2]$, então:

a. calcule a função de distribuição condicional de $X$ dado $B$, cuja fórmula é
$$
\frac{F_X (x|B) = P([X \leq x] ∩[X \leq 2])}{P[X \leq 2]}
$$


b. derivando a resposta obtida no item (a), calcule a função de densidade condicional de $X$
dado $B$,
$$
f (x|B) = \frac{d}{dx} F_X (x|B)
$$

c. usando o item anterior, calcule a esperança condicional de $X$ dado $B$,
$$
E(X|B) = \int_{-\infty}^{\infty} x f (x|B)dx.
$$

## Resposta

a. Para calcular $F_X (x|B)$, 

> $P([X \leq x] ∩[X \leq 2]) = P([X \leq x]) = F_X(x)$

e

> $P[X \leq 2] = F_X(2)$

Logo, 

> $F_X (x|B) = \frac{F_X(x)}{F_X(2)}$

Substituindo, para $1 < x \leq 2$, temos

> $F_X (x|B) = \frac{\int_{1}^{x} \frac{2}{t^3} dt}{\int_{1}^{2} \frac{2}{t^3} dt}$

> $F_X (x|B) = \frac{\left[ -\frac{1}{t^2} \right]_{1}^{x}}{\left[ -\frac{1}{t^2} \right]_{1}^{2}}$

> $F_X (x|B) = \frac{-\frac{1}{x^2} + 1}{-\frac{1}{2} + 1}$

> $F_X (x|B) = \frac{2 - x^2}{2}$

Para $x \leq 1$, temos

> $F_X (x|B) = 0$

Assim,

$$
F_X (x|B) = \begin{cases}
0 & \text{se } x \leq 1, \\
\frac{2 - x^2}{2} & \text{se } 1 < x \leq 2.
\end{cases}
$$

b. Derivando a resposta obtida no item (a), temos

> $f (x|B) = \frac{d}{dx} F_X (x|B)$

Para $1 < x \leq 2$, temos

> $f (x|B) = \frac{d}{dx} \left( \frac{2 - x^2}{2} \right)$

> $f (x|B) = \frac{-2x}{2}$

> $f (x|B) = -x$

Para $x \leq 1$, temos

> $f (x|B) = 0$

Assim,

$$
f (x|B) = \begin{cases}
0 & \text{se } x \leq 1, \\
-x & \text{se } 1 < x \leq 2.
\end{cases}
$$

c. Usando o item anterior, temos

> $E(X|B) = \int_{-\infty}^{\infty} x f (x|B)dx$

> $E(X|B) = \int_{1}^{2} x (-x)dx$

> $E(X|B) = \int_{1}^{2} -x^2dx$

> $E(X|B) = \left[ -\frac{x^3}{3} \right]_{1}^{2}$

> $E(X|B) = -\frac{8}{3} + \frac{1}{3}$

> $E(X|B) = -\frac{7}{3}$






# Exercício 2

Considere as variáveis aleatórias $X$ e $Y$ com densidade conjunta dada por

$$
f_{X,Y} (x, y) = \frac{e^{-\frac{x}{y}}e^{-y}}{y}, \hspace{1cm} \text{onde} \hspace{0.5cm} 0 < x < \infty, 0 < y < \infty
$$

Então:

a. determine a densidade marginal $f_Y$;

b. determine a densidade condicional $f (x|Y = y)$;

c. calcule $P[0 < X < 1|Y = 2]$;

d. calcule a esperança condicional $E(X|Y)$.

## Solução

a. Para determinar a densidade marginal $f_Y$, temos

> $f_Y(y) = \int_{0}^{\infty} f(x, y)dx$

Como $x$ varia de $0$ a $\infty$, temos

> $f_Y(y) = \int_{0}^{\infty} \frac{e^{-\frac{x}{y}}e^{-y}}{y}dx$

> $f_Y(y) = \frac{e^{-y}}{y} \int_{0}^{\infty} e^{-\frac{x}{y}}dx$

> $f_Y(y) = \frac{e^{-y}}{y} \left[ -y e^{-\frac{x}{y}} \right]_{0}^{\infty}$

> $f_Y(y) = \frac{e^{-y}}{y} \left[ -y e^{-\frac{\infty}{y}} + y e^0 \right]$

> $f_Y(y) = \frac{e^{-y}}{y} \left[ 0 + y \right]$

> $f_Y(y) = e^{-y}$

b. Para determinar a densidade condicional $f (x|Y = y)$, temos

> $f (x|Y = y) = \frac{f(x, y)}{f_Y(y)}$

> $f (x|Y = y) = \frac{\frac{e^{-\frac{x}{y}}e^{-y}}{y}}{e^{-y}}$

> $f (x|Y = y) = \frac{e^{-\frac{x}{y}}}{y}$

c. Para calcular $P[0 < X < 1|Y = 2]$, usamos a definicão de probabilidade condicional

> $P[0 < X < 1|Y = 2] = \frac{P[0 < X < 1, Y = 2]}{P[Y = 2]}$

> $P[0 < X < 1|Y = 2] = \frac{\int_{0}^{1} f(x, 2)dx}{f_Y(2)}$

> $P[0 < X < 1|Y = 2] = \frac{\int_{0}^{1} \frac{e^{-\frac{x}{2}}e^{-2}}{2}dx}{e^{-2}}$

> $P[0 < X < 1|Y = 2] = \frac{\frac{e^{-2}}{2} \int_{0}^{1} e^{-\frac{x}{2}}dx}{e^{-2}}$

> $P[0 < X < 1|Y = 2] = \frac{\frac{e^{-2}}{2} \left[ -2e^{-\frac{x}{2}}\right]^1_0}{e^{-2}}$

> $P[0 < X < 1|Y = 2] = \frac{2}{2}(-e^{-\frac{1}{2}}+1)$

> $P[0 < X < 1|Y = 2] = -e^{-\frac{1}{2}} + 1$

d. Para calcular a esperança condicional $E(X|Y)$, temos

> $E(X|Y) = \int^\infty_{-\infty} x \cdot f(x|Y=y)dx$

Como $0<x< \infty$

> $E(X|Y) = \int^\infty_0 x \cdot \frac{e^{-\frac{x}{y}}}{y}dx$

> $E(X|Y) = \frac{1}{y}\int^\infty_0 x \cdot e^{-\frac{x}{y}}dx$

> $E(X|Y) = \frac{1}{y} \left[ \frac{x^2}{2}\cdot -ye^{-\frac{x}{y}} \right]^\infty_0$

> $E(X|Y) = \frac{1}{y} \left[0 \right]$

> $E(X|Y) = \frac{1}{y}$


# Exercício 3
Considere as variáveis aleatórias $X$ e $Y$ com densidade conjunta dada por

$$
f_{X,Y} (x, y) = \begin{cases}
x+y & \text{se } 0 < x < y < 1, \\
0 & \text{caso contrário}.
\end{cases}
$$

Então:

a. determine as densidades marginais $f_X$ e $f_Y$;

b. determine as densidades condicionais $f (x|Y = y)$ e $f (y|X = x)$;

c. calcule as esperanças condicionais $E(X|Y)$ e $E(Y|X)$.

## Solução

a. Para $0<x<y<1$,

Para determinar $f_X$, tem-se que:

> $f_X = \int_{-\infty}^\infty f(x,y)dy$

> $f_X = \int^1_0 x + y dy$

> $f_X = \left[ xy + \frac{y^2}{2} \right]^1_0$

> $f_X = \left[ x + \frac{1}{2} -0\right]$

> $f_X =  x + \frac{1}{2}$

Para determinar $f_Y$, tem-se que

> $f_Y = \int_{-\infty}^\infty f(x,y)dx$

> $f_Y = \int^1_0 x + y dx$

> $f_Y = y + \frac{1}{2}$

b. Para $0<x<y<1$

> $f (x|Y = y) = \frac{f(x,y)}{f_X}$

> $f (x|Y = y) = \frac{x+y}{x + \frac{1}{2}}$

> $f (x|Y = y) = \frac{x+y}{\frac{2x+1}{2}}$

> .....