---
title: "Cecampe-CO/PDDE"
subtitle: "Entrega 1"
author: "Tailine J. S. Nonato"
format: pdf
---

```{r}
if (!require(pacman)) install.packages("pacman")
pacman::p_load(tidyverse, knitr, openxlsx)
#setwd("C:/Users/User/Documents/GitHub/gradest/PDDE/entrega 1")
#setwd("/Users/tailine.nonato/Documents/VSCode/PDDE/entrega 1")
```

# Extração

## Censo Escolar 2022
```{r}	
#censo22 <- read.csv("dados/microdados(...).csv", encoding = "latin1")
#kable(head(censo22))
```

## PDDE 2023
Descrição da manipulação:
- Importação dos dados no Consulta Escola
- Conversão de xls para csv utilizando CloudConvert
- Importação dos dados no R

```{r}
pdde_pagos <- read.csv("ETL/dados/pdde_pagos.csv", skip = 5)
pdde_naopagos <- read.csv("ETL/dados/pdde_naopagos.csv", skip = 5)
```


# Transformação

Censo Escolar 2022 na região Centro-Oeste:
```{r}
censo22_co <- censo22 %>%
    filter(NO_REGIAO == "Centro-Oeste")

write.csv(censo22_co, "dados/censo22_co.csv", row.names = FALSE)
censo22_co <- read.csv("ETL/dados/censo22_co.csv")
```

PDDE 2023 com pagos e não-pagos:
```{r}	
pdde_pagos$fonte <- "pdde_pagos"
pdde_naopagos$fonte <- "pdde_naopagos"
pdde <- rbind(pdde_pagos, pdde_naopagos)
```

Cruzamento de informações Censo e PDDE utilizando o código da escola como chave:
```{r}
censo22_co$CO_ENTIDADE <- as.character(censo22_co$CO_ENTIDADE)
pdde$Código.Escola <- as.character(pdde$Código.Escola)

dados <- censo22_co %>% left_join(pdde, by = c("CO_ENTIDADE" = "Código.Escola"))
```

# Loading/Exportação

```{r}
#| warning: false
#| message: false
#| echo: false

write.csv(dados, "ETL/dados/base_completa.csv")
```