---
title: "Exercícios em Sala"
subtitle: "ANÁLISE DE DADOS CATEGORIZADOS"
author: "Tailine J. S. Nonato"
format: pdf
---

# 28 de março
## Descrição da atividade 
Estimar a proporção de casas com renda menor que 5 u.m. 

Aula de inferências/estimativa de proporção.


```{r}
#| echo: false
#| message: false

if (!require(pacman)) install.packages("pacman")
pacman::p_load(tidyverse,knitr)
```

```{r}
set.seed(4)
n<-10
amostra <- sample(1:90,size=n, replace = FALSE)
salario<- c(9,2,2,8,3,5,8,3,6,8)
carac <- salario<5

df<-data.frame(amostra,salario,carac)
kable(df,align='c')
```

**Estimativa pontual**
```{r}
pia <-sum(df$carac)/10
kable(pia,align='c')
```

**Estimativa do intervalo de confiância**
```{r}
alpha<- 0.1
sup<- pia - qnorm(1-(alpha/2))*sqrt((pia*(1-pia))/n)
inf<- pia + qnorm(1-(alpha/2))*sqrt((pia*(1-pia))/n)

ic <- data.frame(sup,inf)
kable(round(ic,2),align='c')
```

## Descrição da atividade

Jornal; preferem certa marca

$$
\begin{cases}
H_{0}: \mbox{$\pi= 0.6$} \\
H_{1}: \mbox{$\pi > 0.6$}
\end{cases}
$$


**Dados**
```{r}
n=200
carac=156

prop<- carac/n

kable(prop,align='c')
```

**Teste de hipóteses**
```{r}
pib<-0.6
alpha<-0.025

z<- (prop-pib)/sqrt((pib*(1-pib))/n)


kable(z, align = 'c')
kable(z>qnorm(1-(alpha)),align='c')
```

```{r}

sup<- pib - qnorm(1-(alpha))*sqrt((pib*(1-pib))/n)
inf<- pib + qnorm(1-(alpha))*sqrt((pib*(1-pib))/n)

ic <- data.frame(sup,inf)
kable(round(ic,2),align='c')
```