---
title: 'p3'
author: tailine
format: html
---
```{r}
pacman::p_load(tidyverse,car,easyanova,asbio)

(((2*5.5)+(2*7.8))/7)/3

obs1<-c(18.2,18.9,12.9,14.4,
        27.2,24,22.4,22.5,
        15.7,14.5,15.1,14.2,
        41,43.9,36.3,39.9)

fatA1<-factor(c(0.08,0.08,0.08,0.08,
               0.08,0.08,0.08,0.08,
               0.16,0.16,0.16,0.16,
               0.16,0.16,0.16,0.16))
fatB1<- factor(c(40,40,40,40,
               90,90,90,90,
               40,40,40,40,
               90,90,90,90))

df1<-data.frame(fatA1,fatB1,obs1)

anovaaa<-aov(obs1~fatA1*fatB1)
summary(anovaaa)

sum(summary(anovaaa)[[1]][,3])


qqnorm(anovaaa$residuals)
qqline(anovaaa$residuals)

shapiro.test(anovaaa$residuals)

plot(anovaaa$residuals)


leveneTest(obs1~fatA1)
leveneTest(obs1~fatB1)

bartlett.test(obs1~fatA1)
bartlett.test(obs1~fatB1)

tukey.add.test(obs1,fatB1,fatA1)

interaction.plot(fatB1,fatA1,obs1)
boxplot(obs1~fatA1*fatB1)
boxplot(obs1~fatA1)
boxplot(obs1~fatB1)

TukeyHSD(anovaaa)

um=sum(df1[1:4,3])
ab=sum(df1[5:8,3])
ba=sum(df1[9:12,3])
abc=sum(df1[13:16,3])

um
ab
ba
abc
```


# Q 2
```{r}

obs<-c(107,117,122,111,90,116,
        89,101,98,101,95,90,
        116,136,130,122,117,114,
        101,110,104,91,100,94,
        90,112,99,105,110,114,
        96,89,92,78,90,93)
fatA<-factor(rep(c('A','B','C'),each=12))
fatB<-factor(rep(c('M','P'),each=6,times=3))
bloco<-factor(rep(c(1:6),times=6))

df<-data.frame(fatA,bloco,fatB,obs)

anova<-aov(obs~fatA*fatB+Error(bloco/fatA))
summary(anova)

res<-aov(obs~fatA*fatB+bloco:fatA)
summary(res)

anova2<- ea2(df,design = 5)
anova2

qqnorm(res$residuals)
qqline(res$residuals)

shapiro.test(res$residuals)

plot(res$residuals)

leveneTest(obs~bloco)
leveneTest(obs~fatA)
leveneTest(obs~fatB)


bartlett.test(obs~bloco)
bartlett.test(obs~fatA)
bartlett.test(obs~fatB)

tukey.add.test(obs,fatA,bloco)
tukey.add.test(obs,fatB,bloco)
tukey.add.test(obs,fatA,fatB)

interaction.plot(fatA,fatB,obs)
boxplot(obs~fatA*fatB)
boxplot(obs~fatA)
boxplot(obs~fatB)


```
