---
title: "CheatSheet - Unidade 1"
subtitle: "Cálculo de Probabilidade 2"
author: "Tailine J. S. Nonato"
format: pdf
---

# Conteúdo

Dado $X$ e $Y$ variáveis aleatórias:

## Esperança Condicional

- $X$ e $Y$ v.a.'s discretas
$$
E(X|Y=y) = \sum^{\infty}_{n=1} x \cdot f(x|Y=y_n)dx
$$

- $X$ e/ou $Y$ v.a.'s contínuas
$$
E(X|Y=y) = \int^{\infty}_{-\infty} x \cdot f(x|Y=y)dx = \int^{\infty}_{-\infty} x \cdot dF(x|Y=y)
$$

$$
E(X) = E(E(X|Y)) = \sum^{\infty}_{n=1} P(Y=y_n) \cdot E(X|Y=y_n)
$$

## Função de Densidade de Probabilidade Condicional

$$
f(x|Y=y) = \frac{f(x,y)}{f(y)}
$$

### Função de Densidade de Probabilidade Conjunta

$$
f(x,y) = \frac{\partial^2 F(x,y)}{\partial x \partial y}
$$

### Função de Densidade de Probabilidade Marginal

$$
f(x) = \int^{\infty}_{-\infty} f(x,y)dy
$$

$$
f(y) = \int^{\infty}_{-\infty} f(x,y)dx
$$

## Função de Distribuição Acumulada Condicional

$$
F(x|Y=y) = P(X \leq x|Y=y) = \int^{x}_{-\infty} f(x|Y=y)dx
$$


### Função de Distribuição Acumulada Conjunta

$$
F(x,y) = P(X \leq x, Y \leq y) = \int^{x}_{-\infty} \int^{y}_{-\infty} f(x,y)dxdy
$$

### Função de Distribuição Acumulada Marginal

$$
F(x) = \int^{\infty}_{-\infty} F(x,y)dy
$$

$$
F(y) = \int^{\infty}_{-\infty} F(x,y)dx
$$


# Distribuições
:::: {.columns}

::: {.column width="50%"}

## Bernoulli

- $X \sim Bernoulli(p)$
- $P(X=1) = p$
- $P(X=0) = 1-p$
- $E(X) = p$
- $Var(X) = p(1-p)$


## Binomial

- $X \sim Binomial(n,p)$
- $P(X=k) = \binom{n}{k} \cdot p^k \cdot (1-p)^{n-k}$
- $E(X) = n \cdot p$
- $Var(X) = n \cdot p \cdot (1-p)$


## Uniforme

- $X \sim U(a,b)$
- $f(x) = \frac{1}{b-a}$
- $E(X) = \frac{a+b}{2}$
- $Var(X) = \frac{(b-a)^2}{12}$
- $F(x) = \frac{x-a}{b-a}$

## Beta

- $X \sim Beta(\alpha, \beta)$
- $f(x) = \frac{x^{\alpha-1} \cdot (1-x)^{\beta-1}}{B(\alpha, \beta)}$
- $E(X) = \frac{\alpha}{\alpha+\beta}$
- $Var(X) = \frac{\alpha \cdot \beta}{(\alpha+\beta)^2 \cdot (\alpha+\beta+1)}$


## Normal

- $X \sim N(\mu, \sigma^2)$
- $f(x) = \frac{1}{\sqrt{2\pi}\sigma} \cdot e^{-\frac{(x-\mu)^2}{2\sigma^2}}$
- $E(X) = \mu$
- $Var(X) = \sigma^2$


## Cauchy

- $X \sim Cauchy(\mu, \gamma)$
- $f(x) = \frac{1}{\pi \gamma \left[1 + \left(\frac{x-\mu}{\gamma}\right)^2\right]}$
- $E(X)$ não existe
- $Var(X)$ não existe


## Poisson

- $X \sim Poisson(\lambda)$
- $P(X=k) = \frac{e^{-\lambda} \cdot \lambda^k}{k!}$
- $E(X) = \lambda$
- $Var(X) = \lambda$


## Exponencial

- $X \sim Exp(\lambda)$
- $f(x) = \lambda \cdot e^{-\lambda x}$
- $E(X) = \frac{1}{\lambda}$
- $Var(X) = \frac{1}{\lambda^2}$
- $F(x) = 1 - e^{-\lambda x}$

## Geométrica

- $X \sim Geom(p)$
- $P(X=k) = (1-p)^{k-1} \cdot p$
- $E(X) = \frac{1}{p}$
- $Var(X) = \frac{1-p}{p^2}$
- $F(x) = 1 - (1-p)^{\lfloor x \rfloor}$


## Hipergeométrica

- $X \sim Hipergeom(N,M,n)$
- $P(X=k) = \frac{\binom{M}{k} \cdot \binom{N-M}{n-k}}{\binom{N}{n}}$
- $E(X) = n \cdot \frac{M}{N}$
- $Var(X) = n \cdot \frac{M}{N} \cdot \frac{N-M}{N} \cdot \frac{N-n}{N-1}$
- $F(x) = \sum^{x}_{k=0} \frac{\binom{M}{k} \cdot \binom{N-M}{n-k}}{\binom{N}{n}}$